export const fileIcons: any = {
  "image/jpeg": "mdi-image",
  "image/png": "mdi-image",
  "image/gif": "mdi-image",
  "image/bmp": "mdi-image",
  "application/pdf": "mdi-file-pdf",
  "application/msword": "mdi-file-word",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document": "mdi-file-word",
  "application/vnd.oasis.opendocument.text": "mdi-file-word",
  "application/vnd.ms-powerpoint": "mdi-file-powerpoint",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation": "mdi-file-powerpoint",
  "application/vnd.oasis.opendocument.presentation": "mdi-file-powerpoint",
  "application/vnd.ms-excel": "mdi-file-excel",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": "mdi-file-excel",
  "application/vnd.oasis.opendocument.spreadsheet": "mdi-file-excel",
  "application/xml": "mdi-file-code",
  "application/json": "mdi-file-code",
  "application/xhtml+xml": "mdi-file-code",
  "text/html": "mdi-file-code",
  "text/xml": "mdi-file-code"
};
