info:
  application:
    name: '@project.artifactId@'
    version: '@project.version@'

server:
  port: ${MIRANUM_PROCESS_INTEGRATION_EXAMPLE_PORT}

camunda:
  autoDeploy:
    enabled: true
  bpm:
    client:
      base-url: http://localhost:8083/engine-rest
      disable-backoff-strategy: ${WORKER_BACKOFF_STRATEGIE_DISABLED:false}

dev:
  bpm-crafters:
    process-api:
      adapter:
        c7remote:
          enabled: true
          service-tasks:
            delivery-strategy: remote_scheduled
            schedule-delivery-fixed-rate-in-seconds: 1
            worker-id: embedded-worker
            lock-time-in-seconds: 10
          user-tasks:
            schedule-delivery-fixed-rate-in-seconds: 1
            delivery-strategy: remote_scheduled

camunda.bpm.client:
  base-url: http://localhost:8083/engine-rest/

feign:
  client:
    config:
      default:
        url: "http://localhost:8083/engine-rest/"

miranum:
  security:
    server:
      base-url: ${SSO_BASE_URL}
      realm: ${SSO_REALM}
      user-name-attribute: email
    client:
      clientId: ${SSO_INQUIRY_WORKER_CLIENT_ID}
      clientSecret: ${SSO_INQUIRY_WORKER_CLIENT_SECRET}
    permittedUrls:
      - "/error"
      - "/actuator/**"
      - "/swagger-ui/index.html" # allow access to swagger
      - "/swagger-ui*/*swagger-initializer.js" # allow access to swagger
      - "/swagger-ui*/**" # allow access to swagger
      - "/v3/api-docs/*" # allow access to swagger
      - "/v3/api-docs" # allow access to swagger

io.miragon.miranum.inquiry:
  deployment:
    deployment-resource-pattern: "classpath:processes/**/*.bpmn"

logging:
  level:
    root: info
