openapi: 3.0.0
info:
  version: 1.1.3
  title: Submission API für Antragsverfahren und Berichtspflichten
  description: |
    Die FIT-Connect Submission API ermöglicht das Einreichen von Anträgen und Berichten aus vorgelagerten Systemen (z. B. Onlineantragsdiensten, Fachportalen oder Berichtssystemen) an die Systeme der Verwaltung zur elektronischen Verfahrensbearbeitung (z. B. Fachverfahren, Dokumentenmanagementsysteme oder Prozessplattformen).
  contact:
    name: FITKO
    url: 'https://docs.fitko.de/fit-connect/contact'
  license:
    url: 'https://creativecommons.org/licenses/by-sa/4.0/'
    name: Creative Commons Attribution Share Alike 4.0 (CC BY-SA 4.0)
  termsOfService: 'https://docs.fitko.de/fit-connect/docs/details/terms-of-use-testing/'
servers:
  - url: 'https://submission-api-testing.fit-connect.fitko.dev'
    description: FIT-Connect Testumgebung
tags:
  - name: Zustellpunktverwaltung
    description: 'Unter dieser Gruppe sind alle Endpunkte organisiert, über welche Zustellpunkte verwaltet werden können.'
  - name: Einreichungsübermittlung
    description: 'Diese Gruppe enthält alle Endpunkte, die für das Versenden von Einreichungen an einen Zustellpunkt notwendig sind.'
  - name: Einreichungsempfang
    description: 'Diese Gruppe umfasst alle Endpunkte, die für den Empfang und die Abfrage von Einreichungen notwendig sind.'
  - name: Technisch
    description: 'Unter dieser Gruppe sind alle Endpunkte organisiert, die technische Informationen über die Instanz des Zustelldienstes liefern.'
  - name: Internal
    description: 'Unter dieser Gruppe werden Endpunkte gelistet, die FIT-Connect intern sind und API-Clients nicht zur Verfügung stehen.'
paths:
  /v1/destinations:
    get:
      operationId: get-my-destinations
      summary: Eigene Zustellpunkte auflisten
      description: Mit diesem Request können alle selbst angelegten Zustellpunkte sowie deren Konfigurationen abgerufen werden.
      tags:
        - Internal
      security:
        - OAuth2:
            - 'subscribe:destination:<id>'
            - 'manage:destination:<id>'
    post:
      operationId: create-destination
      summary: Zustellpunkt anlegen
      description: |
        Erstellung eines neuen Zustellpunktes mit entsprechender Konfiguration zum Empfang von Einreichungen. Ein detaillierte Beschreibung ist in der [Dokumentation](https://docs.fitko.de/fit-connect/docs/getting-started/receiving/destination) zu finden.
      tags:
        - Internal
      security:
        - OAuth2:
            - 'create:destination'
  '/v1/destinations/{destinationId}':
    get:
      operationId: get-destination-info
      summary: Zustellpunkt abfragen
      description: Ruft die Details eines Zustellpunktes ab.
      tags:
        - Einreichungsübermittlung
      security:
        - OAuth2:
            - 'subscribe:destination:<id>'
            - 'manage:destination:<id>'
            - 'send:region:DE<region-id>+send:service:<service-uri>'
            - 'send:region:DE<region-id>'
    put:
      operationId: update-destination
      summary: Zustellpunkt vollständig aktualisieren
      description: 'Ermöglicht es, einen Zustellpunkt vollständig zu aktualisieren.'
      tags:
        - Internal
      security:
        - OAuth2:
            - 'manage:destination:<id>'
    patch:
      operationId: patch-destination
      summary: Zustellpunkt partiell aktualisieren
      description: |
        Ermöglicht es einen Zustellpunkt partiell zu aktualisieren. Ein Beispiel wäre die Änderung des Feldes `encryptionKid` bei Schlüssel-Rollover.
      tags:
        - Internal
      security:
        - OAuth2:
            - 'manage:destination:<id>'
    delete:
      operationId: delete-destination
      summary: Zustellpunkt löschen
      description: 'Dieser Endpunkt ermöglicht es, einen Zustellpunkt zu löschen.'
      tags:
        - Internal
      security:
        - OAuth2:
            - 'manage:destination:<id>'
  '/v1/destinations/{destinationId}/keys':
    post:
      operationId: add-destination-key
      summary: Fügt dem Zustellpunkt einen JWK hinzu.
      tags:
        - Internal
      security:
        - OAuth2:
            - 'manage:destination:<id>'
  '/v1/destinations/{destinationId}/keys/{keyId}':
    get:
      operationId: get-destination-key
      summary: Ruft einen JWK des Zustelldienstes ab
      description: 'Ermöglicht es, Public Keys eines Zustellpunktes abzufragen.'
      tags:
        - Einreichungsübermittlung
  '/v1/cases/{caseId}/events':
    get:
      operationId: get-case-events
      summary: Event Log auslesen
      description: |
        Über diesen Endpunkt kann der [Event Log](https://docs.fitko.de/fit-connect/docs/getting-started/event-log/) eines Vorgangs abgerufen werden, um z.B. den Status des Vorgangs zu überprüfen.
      tags:
        - Einreichungsempfang
        - Einreichungsübermittlung
      security:
        - OAuth2:
            - 'subscribe:destination:<id>'
            - 'manage:destination:<id>'
            - 'send:region:DE<region-id>+send:service:<service-uri>'
            - 'send:region:DE<region-id>'
    post:
      operationId: send-case-event
      summary: Event senden
      description: |
        Als empfangendes System ist es notwendig die Einreichung entweder zu akzeptieren oder abzulehnen und dadurch die Zustellung abzuschließen. Hierfür muss ein entsprechendes Event im Vorgang hinterlegt werden, indem es den Zustelldienst gesendet wird. Dieses Event kann nach der Validierung der Rahmenstruktur der Einreichung versendet werden, wie [hier](https://docs.fitko.de/fit-connect/docs/receiving/process-and-acknowledge) beschrieben ist.
      tags:
        - Einreichungsempfang
      security:
        - OAuth2:
            - 'subscribe:destination:<id>'
  /v1/submissions:
    get:
      operationId: get-submissions-for-pickup
      summary: Abholbereite - im Status submitted - Einreichungen auflisten
      description: Mit diesem Request werden alle abholbereiten Einreichungen sowie deren Zustellpunkte aufgelistet.
      tags:
        - Einreichungsempfang
      security:
        - OAuth2:
            - 'subscribe:destination:<id>'
    post:
      operationId: create-submission
      summary: Einreichung erstellen
      description: |
        Dieser Endpunkt ist der erste, initiale Schritt zum Erstellen einer Einreichung. Danach können Anlagen hochgeladen und schließlich die Einreichung an den Zustellpunkt versendet werden, der in diesem Endpunkt angegeben wurde.
      tags:
        - Einreichungsübermittlung
      security:
        - OAuth2:
            - 'send:region:DE<region-id>+send:service:<service-uri>'
            - 'send:region:DE<region-id>'
  '/v1/submissions/{submissionId}':
    get:
      operationId: get-submission
      summary: Einreichung abrufen
      description: |
        Hierüber können die Fachdaten, Metadaten und Strukturinformation einer Einreichung vom Status submitted oder forwarded abgefragt und dann ausgewertet werden. Eine Beschreibung, wie diese Daten weiter verarbeitet werden ist [hier](https://docs.fitko.de/fit-connect/docs/getting-started/receiving/download-submission/) zu finden.
      tags:
        - Einreichungsempfang
      security:
        - OAuth2:
            - 'subscribe:destination:<id>'
    put:
      operationId: submit-submission
      summary: Einreichung versenden
      description: |
        Über den Aufruf dieses Endpunktes wird eine vollständige Einreichung an den Zustellpunk versendet. Als sendendes System kann der Status der Einreichung überprüft werden, um herauszufinden, ob die Einreichung den Zustellpunkt erreicht hat bzw. von diesem akzeptiert wurde.
      tags:
        - Einreichungsübermittlung
      security:
        - OAuth2:
            - 'send:region:DE<region-id>+send:service:<service-uri>'
            - 'send:region:DE<region-id>'
  '/v1/submissions/{submissionId}/attachments/{attachmentId}':
    get:
      operationId: get-submission-attachment
      summary: Anlage abrufen
      description: |
        Ruft eine Anlage einer Einreichung vom Status submitted oder forwarded im JOSE-Format ab. Genaueres ist in der [Dokumentation](https://docs.fitko.de/fit-connect/docs/getting-started/receiving/download-submission/) beschrieben
      tags:
        - Einreichungsempfang
      security:
        - OAuth2:
            - 'subscribe:destination:<id>'
    put:
      operationId: add-submission-attachment
      summary: Anlage hinzufügen
      description: |
        Hochladen der in `announcedAttachments` angekündigten Anlage im JOSE-Format unter der mitgeteilten UUID. Genaueres ist in der [Dokumentation](https://docs.fitko.de/fit-connect/docs/getting-started/sending/attachments/) beschrieben.
      tags:
        - Einreichungsübermittlung
      security:
        - OAuth2:
            - 'send:region:DE<region-id>+send:service:<service-uri>'
            - 'send:region:DE<region-id>'
  /v1/info:
    get:
      operationId: get-info
      summary: Rufe technische Serviceinformationen der Instanz ab
      description: Für Debugging oder Informationszwecke angebotener Endpunkt
      tags:
        - Technisch
  /.well-known/jwks.json:
    get:
      operationId: get-jwks.json
      summary: Rufe die öffentlichen Schlüssel des Zustelldienstes ab
      description: Kann z.B. zur Validierung der SETs des Zustelldienstes genutzt werden.
      tags:
        - Technisch
        - Einreichungsübermittlung
        - Einreichungsempfang
components:
  securitySchemes:
    OAuth2:
      description: 'Authentifizierungsmethode, um den Zugriff nach RFC8725 zu autorisieren'
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://auth-testing.fit-connect.fitko.dev/token'
          scopes:
            'subscribe:destination:<id>': Erlaubt die Abholung von Anträgen und Dokumenten (Anhängen) des Zustellpunktes
            'manage:destination:<id>': Erlaubt die Verwaltung des Zustellpunktes
            'send:region:DE<region-id>+send:service:<service-uri>': Erlaubt das Versenden von Anträgen an Zustellpunkte mit Region/Leistung Kombination
            'send:region:DE<region-id>': Erlaubt das Versenden von Anträgen an Zustellpunkte der Region
            'create:destination': Erlaubt das Anlegen von Zustellpunkten