@startuml
class Camunda8ElementTemplate {

    - String name
    - String id
    - String description
    - String documentationRef
    - Integer version
    - Boolean isDefault
    - List<String> appliesTo
    - ElementType elementType
    - Metadata metadata
    - Boolean entriesVisible
    - List<Group> groups

    - Property property
    - Icon icon
    
}
Camunda8ElementTemplate::property -- Property
Camunda8ElementTemplate::metadata -- Metadata
Camunda8ElementTemplate::group -- Group
Camunda8ElementTemplate::elementType -- ElementType
Camunda8ElementTemplate::icon -- Icon

class Metadata {}

class Group {

    - String id
    - String label

}

class ElementType {

    - String value

}

class Icon {

    String contents

}

class Property {

    - String label
    - String id
    - String description
    - String group
    - String type
    - String feel
    - String language
    - Boolean optional
    - Object value
    - Boolean editable
    - List<Item> choices
    - Constraints constraints
    - Condition condition
    - Binding binding

}
Property::item -- Item
Property::constraints -- Constraints
Property::condition -- Condition
Property::binding -- Binding

class Item {

    - String name
    - String value

}

class Condition {

    - String TYPE = "simple"
    - String property
    - Object equals
    - List<Object> oneOf

}

class Constraints {

    - Boolean notEmpty
    - Double minLength
    - Double maxLength
    - Pattern pattern

}
Constraints::pattern -- Pattern

class Pattern {

    - String value
    - String message

}

class Binding {

    - Type type
    - String name
    - String source
    - String key

}
Binding::type -- Type

enum Type {

    PROPERTY
    ZEEBE_TASKDEFINITION_TYPE
    ZEEBE_INPUT
    ZEEBE_OUTPUT
    ZEEBE_TASKHEADER

}

@enduml
