@startuml
class Camunda8ElementTemplate {

    - String name
    - String id
    - String description
    - Integer version
    - Boolean isDefault
    - List<String> appliesTo
    - ElementType elementType
    - Metadata metadata
    - Boolean entriesVisible
    - List<Group> groups
    - String documentationRef
    - List<Property> properties
    - Icon icon

}
Camunda8ElementTemplate::properties -- Property
Camunda8ElementTemplate::metadata -- Metadata
Camunda8ElementTemplate::group -- Group
Camunda8ElementTemplate::elementType -- ElementType
Camunda8ElementTemplate::icon -- Icon

class Metadata {}

class Group {

    - String id
    - String label

}

class ElementType {

    - String value

}

class Icon {

    String contents

}

class Property {

    - String id
    - Object value
    - String description
    - String label
    - String type
    - Boolean editable
    - List<Choice> choices
    - Constraints constraints
    - String group
    - Condition condition
    - Binding binding
    - Boolean optional
    - String feel
    - String language

}
Property::choices -- Choice
Property::constraints -- Constraints
Property::condition -- Condition
Property::binding -- Binding

class Choice {

    - String name
    - String value

}

class Condition {

    - String TYPE = "simple"
    - String property
    - Object equals
    - List<Object> oneOf

}

together {
    class Constraints {

        - Boolean notEmpty
        - Double minLength
        - Double maxLength
        - String pattern

    }

    class Pattern {

        - String value
        - String message

    }
}

class Binding {

    - Type type
    - String name
    - String source
    - String key

}
Binding::type -- Type

enum Type {

    PROPERTY
    ZEEBE_TASKDEFINITION_TYPE
    ZEEBE_TASKDEFINITION_RETRIES
    ZEEBE_INPUT
    ZEEBE_OUTPUT
    ZEEBE_PROPERTY
    ZEEBE_TASKHEADER

}

@enduml
