// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DwfDateInput: typeof import('./src/components/DwfDateInput.vue')['default']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VTextField: typeof import('vuetify/lib')['VTextField']
    VTooltip: typeof import('vuetify/lib')['VTooltip']
  }
}
