package io.miragon.miranum.integrations.example.c7;

import okhttp3.Interceptor;
import okhttp3.Request;
import okhttp3.Response;
import org.camunda.bpm.client.interceptor.ClientRequestInterceptor;
import org.camunda.community.rest.client.invoker.ApiClient;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.io.IOException;

@Configuration
public class AuthInterceptor {

    @Bean
    public ClientRequestInterceptor interceptor() {
        return context -> {
            context.addHeader("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJwbS10NlhjYXM1ZU41NXNfNmZmTzhKY3hEMXVrSVY0d1VRTmFQZjY4YkU4In0.eyJleHAiOjE2NzU3MDIxNTksImlhdCI6MTY3NTcwMTg1OSwianRpIjoiNzc4ZTBkNTYtNmM1YS00ZWM3LTg4ZWUtMzI3YmVlZGI1MDg1IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2F1dGgvcmVhbG1zL2Zvcm1zLWZsb3ctYWkiLCJhdWQiOlsiZm9ybXMtZmxvdy13ZWIiLCJjYW11bmRhLXJlc3QtYXBpIiwiYWNjb3VudCJdLCJzdWIiOiI2OGNhNmI0OS0yOTg3LTRiNjgtYWJiNy0xNzM1ZDk5NGYxMTgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJmb3Jtcy1mbG93LXdlYiIsInNlc3Npb25fc3RhdGUiOiJjNmZlY2RkMC0yYWI4LTQwZDAtYmI5Mi1iZTIyYmQ1NDFiNzIiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJmb3Jtcy1mbG93LXdlYiI6eyJyb2xlcyI6WyJmb3Jtc2Zsb3ctZGVzaWduZXIiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwgY2FtdW5kYS1yZXN0LWFwaSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicm9sZSI6WyJmb3Jtc2Zsb3ctZGVzaWduZXIiXSwibmFtZSI6IkRlc2lnbmVyIEZGQSIsImdyb3VwcyI6WyIvY2FtdW5kYS1hZG1pbiIsIi9mb3Jtc2Zsb3cvZm9ybXNmbG93LWRlc2lnbmVyIl0sInByZWZlcnJlZF91c2VybmFtZSI6ImZvcm1zZmxvdy1kZXNpZ25lciIsImdpdmVuX25hbWUiOiJEZXNpZ25lciIsImZhbWlseV9uYW1lIjoiRkZBIiwiZW1haWwiOiJmb3Jtc2Zsb3ctZGVzaWduZXJAZXhhbXBsZS5jb20ifQ.FnWIXYSQB3psoDrfyzOxg5J2ijpmS-HDq8GBV1OSBry9Dc4ubUYSruH9CHRlfq07sVoDzts_MTJGov1ErFBXXvIFP1HOt_z1mNUZZTHxm-rmghvInzUDIejHMOnFU1n8be35J1qYtRRcN4dGcl99bbTF1fvi3yjo4-pxN1mo6VEOKUWvHxPN8h0rs3iX_oh9dZi8GiSY0-oj5ekrcma4rNGHMVJ2ApXHzX0k75BZDO0kPH1a2ZMWXnIx3Pni5zhsY0SZylfj01AOomFC99r70zbfG1ZsQGfZu0DBRdCkCmrBHfua1EMSZ_u6kqoGbrYQywOKkQpsnGBqHg2B0ix_Rg");
        };
    }

    @Autowired
    public void createApiClient(final ApiClient apiClient) {
        apiClient.setHttpClient(apiClient.getHttpClient().newBuilder().addInterceptor(this::intercept).build())
    }

    public Response intercept(final Interceptor.Chain chain) throws IOException {
        final Request originalRequest = chain.request();
        final Request requestWithToken = originalRequest.newBuilder()
                .header("Authorization", "Bearer " + "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJwbS10NlhjYXM1ZU41NXNfNmZmTzhKY3hEMXVrSVY0d1VRTmFQZjY4YkU4In0.eyJleHAiOjE2NzU3MDIxNTksImlhdCI6MTY3NTcwMTg1OSwianRpIjoiNzc4ZTBkNTYtNmM1YS00ZWM3LTg4ZWUtMzI3YmVlZGI1MDg1IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2F1dGgvcmVhbG1zL2Zvcm1zLWZsb3ctYWkiLCJhdWQiOlsiZm9ybXMtZmxvdy13ZWIiLCJjYW11bmRhLXJlc3QtYXBpIiwiYWNjb3VudCJdLCJzdWIiOiI2OGNhNmI0OS0yOTg3LTRiNjgtYWJiNy0xNzM1ZDk5NGYxMTgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJmb3Jtcy1mbG93LXdlYiIsInNlc3Npb25fc3RhdGUiOiJjNmZlY2RkMC0yYWI4LTQwZDAtYmI5Mi1iZTIyYmQ1NDFiNzIiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJmb3Jtcy1mbG93LXdlYiI6eyJyb2xlcyI6WyJmb3Jtc2Zsb3ctZGVzaWduZXIiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwgY2FtdW5kYS1yZXN0LWFwaSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicm9sZSI6WyJmb3Jtc2Zsb3ctZGVzaWduZXIiXSwibmFtZSI6IkRlc2lnbmVyIEZGQSIsImdyb3VwcyI6WyIvY2FtdW5kYS1hZG1pbiIsIi9mb3Jtc2Zsb3cvZm9ybXNmbG93LWRlc2lnbmVyIl0sInByZWZlcnJlZF91c2VybmFtZSI6ImZvcm1zZmxvdy1kZXNpZ25lciIsImdpdmVuX25hbWUiOiJEZXNpZ25lciIsImZhbWlseV9uYW1lIjoiRkZBIiwiZW1haWwiOiJmb3Jtc2Zsb3ctZGVzaWduZXJAZXhhbXBsZS5jb20ifQ.FnWIXYSQB3psoDrfyzOxg5J2ijpmS-HDq8GBV1OSBry9Dc4ubUYSruH9CHRlfq07sVoDzts_MTJGov1ErFBXXvIFP1HOt_z1mNUZZTHxm-rmghvInzUDIejHMOnFU1n8be35J1qYtRRcN4dGcl99bbTF1fvi3yjo4-pxN1mo6VEOKUWvHxPN8h0rs3iX_oh9dZi8GiSY0-oj5ekrcma4rNGHMVJ2ApXHzX0k75BZDO0kPH1a2ZMWXnIx3Pni5zhsY0SZylfj01AOomFC99r70zbfG1ZsQGfZu0DBRdCkCmrBHfua1EMSZ_u6kqoGbrYQywOKkQpsnGBqHg2B0ix_Rg")
                .build();
        return chain.proceed(requestWithToken);
    }


}
