// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DwfFilePreview: typeof import('./src/components/DwfFilePreview.vue')['default']
    DwfMultiFileInput: typeof import('./src/components/DwfMultiFileInput.vue')['default']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardText: typeof import('vuetify/lib')['VCardText']
    VCardTitle: typeof import('vuetify/lib')['VCardTitle']
    VFileInput: typeof import('vuetify/lib')['VFileInput']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VImg: typeof import('vuetify/lib')['VImg']
    VTooltip: typeof import('vuetify/lib')['VTooltip']
  }
}
